version: '3.1'
services:
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
  mysql:
    image: mysql
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: user_details
      # So you don't have to use root, but you can if you like
      MYSQL_USER: user
      # You can use whatever password you like
      MYSQL_PASSWORD: password
      # Password for root access
      MYSQL_ROOT_PASSWORD: password
  api:
    restart: always
    working_dir: /go/src/github.com/viknesh-nm/sellerapp
    env_file: ${GOPATH}/src/github.com/viknesh-nm/sellerapp/conf/conf.env
    command: go run main.go
    image: api
    ports: 
      - "9090:9090"
    depends_on:
      - mysql
      - mongo
    build:
      context: ${GOPATH}/src/github.com/viknesh-nm/sellerapp
      dockerfile: Dockerfile
    volumes:
      - ${GOPATH}/src/github.com/viknesh-nm/sellerapp:/go/src/github.com/viknesh-nm/sellerapp
